---
- name: Install LAMP stack on CentOS 7.6
  hosts: all
  become: yes
  tasks:
    - name: Ensure EPEL repository is enabled
      yum:
        name: epel-release
        state: present

    - name: Ensure Python MySQL dependencies are installed
      yum:
        name:
          - MySQL-python
        state: present

    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Ensure MySQL server is installed
      yum:
        name: mariadb-server
        state: present

    - name: Ensure MySQL server is started and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install PHP and required PHP modules
      yum:
        name: 
          - php
          - php-mysql
          - php-fpm
        state: present

    - name: Restart Apache to load PHP module
      service:
        name: httpd
        state: restarted

    - name: Create MySQL database
      mysql_db:
        name: testdb
        state: present

    - name: Create MySQL user
      mysql_user:
        name: testuser
        password: testpassword
        priv: 'testdb.*:ALL'
        state: present

    - name: Create PHP info file
      copy:
        dest: /var/www/html/info.php
        content: |
          <?php
          phpinfo();
          ?>

    - name: Create PHP MySQL connection test file
      copy:
        dest: /var/www/html/testdb.php
        content: |
          <?php
          $servername = "localhost";
          $username = "testuser";
          $password = "testpassword";
          $dbname = "testdb";

          // Create connection
          $conn = new mysqli($servername, $username, $password, $dbname);

          // Check connection
          if ($conn->connect_error) {
            die("Connection failed: " . $conn->connect_error);
          }
          echo "Connected successfully";
          ?>
